[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sisana"
authors = [
    {name = "Nolan Newman", email = "nolan.newman@ncmm.uio.no"},
]
version = "1.7.2post1"
description = "A command line interface tool to reconstruct and analyze single sample networks."
readme = "README.md"
requires-python = ">=3.9.0"
keywords = ["transcription-factors", "gene-regulatory-network", "panda", "lioness"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
dependencies = [
    "numpy>=1.26.4,<2",
    "pandas>=2.2.2,<3",
    "netZooPy>=0.10.6,<0.11",
    "scikit-learn>=1.5.1,<2",
    "scikit-survival>=0.23.0,<0.24",
    "matplotlib>=3.8.0,<4",
    "pathlib>=1.0.1,<2",
    "gseapy==1.1.3",
    "seaborn>=0.13.2,<0.14",
    "adjustText>=1.2.0,<2",
    "pyyaml>=6.0.2,<7",
    "pingouin>=0.5.5,<0.6",
    "qnorm>=0.9.0",
    "statannotations>=0.7.1,<0.8",
    "requests>=2.32.3,<3",
    "tqdm>=4.67.1,<5"
]
license = "MIT"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:.*pkg_resources is deprecated as an API*:DeprecationWarning:netZooPy",
]

[tool.setuptools.packages.find]
where = ["."] 
include = ["sisana", 
    "sisana.docs",    
    "sisana.exceptions",    
    "sisana.generate",    
    "sisana.reconstruct",    
    "sisana.postprocessing", 
    "sisana.preprocessing", 
    "sisana.postprocessing.post", 
    "sisana.analyze_networks",
    "sisana.analyze_networks.analyze", 
    "sisana.analyze_networks.genesets",
    "sisana.example_input"] 
namespaces = false  # to disable scanning PEP 420 namespaces (true by default)

[project.scripts]
sisana = "sisana.sisana:cli"

[project.urls]
Repository = "https://github.com/kuijjerlab/sisana/"
